renderPath = "tmpl"
[default]
   pathBeego = "."
   pathSula = "."
[[descriptor]]
    module = "controllers"
    srcName = "bee_default_controller.go.tmpl"
    dstPath = "{{pathBeego}}/controllers/bee_default_controller.go"
    once = true
[[descriptor]]
    module = "controllers"
    srcName = "controller.go.tmpl"
    dstPath = "{{pathBeego}}/controllers/{{modelName}}.go"
[[descriptor]]
    module = "models"
    srcName = "bee_default_model.go.tmpl"
    dstPath = "{{pathBeego}}/models/bee_default_model.go"
    once = true
[[descriptor]]
    module = "models"
    srcName = "model.go.tmpl"
    dstPath = "{{pathBeego}}/models/{{modelName}}.go"
[[descriptor]]
    module = "routers"
    srcName = "router.go.tmpl"
    dstPath = "{{pathBeego}}/routers/{{modelName}}.go"
[[descriptor]]
    module = "sulaList"
    srcName = "list.tsx.tmpl"
    dstPath = "{{pathSula}}/{{modelName}}/list.tsx"
[[descriptor]]
    module = "sulaForm"
    srcName = "formconfig.tsx.tmpl"
    dstPath = "{{pathSula}}/{{modelName}}/formconfig.tsx"
[[descriptor]]
    module = "sulaCreate"
    srcName = "create.tsx.tmpl"
    dstPath = "{{pathSula}}/{{modelName}}/create.tsx"
[[descriptor]]
    module = "sulaUpdate"
    srcName = "update.tsx.tmpl"
    dstPath = "{{pathSula}}/{{modelName}}/update.tsx"
[[descriptor]]
    module = "sulaInfo"
    srcName = "info.tsx.tmpl"
    dstPath = "{{pathSula}}/{{modelName}}/info.tsx"
[[descriptor]]
    module = "mysqlUp"
    srcName = "up.sql.tmpl"
    dstPath = "{{pathBeego}}/sql/{{modelName}}_up.sql"
    script = "bee pro migration --sql={{pathBeego}}/sql/{{modelName}}_up.sql"
[[descriptor]]
    module = "mysqlDown"
    srcName = "down.sql.tmpl"
    dstPath = "{{pathBeego}}/sql/{{modelName}}_down.sql"


